const BASEURL = 'http://15.206.95.141:8000/'
export const DEPARTMENTSAPIS = BASEURL+'/api/user/department/';
export const GETPROJECTDATAAPIS = BASEURL+'/api/project/projects/';
export const CLIENTDATAAPIS = BASEURL+'/api/project/clients/';
export const POSTPROJECTDATAAPIS = BASEURL+'/api/project/projects/';
export const LOGINPOSTAPIS = BASEURL+'/api/user/login/';
export const POSTMANDAYSDATA = BASEURL+'/api/operation/projects/estimate/';
export const RESETPASSWORD = BASEURL+'/api/user/reset-password/';
export const USERLIST = BASEURL+'/api/user/api/users-list/';
export const MANDAYSUPDATE = BASEURL + '/api/operation/projects/estimate/'
export const PROJECTTYPES = BASEURL + '/api/project/project_type'